# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price_tag_analyzer/grpc_compiled/PriceTagAnalyzerService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>price_tag_analyzer/grpc_compiled/PriceTagAnalyzerService.proto\"\x1d\n\nImageChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\'\n\x07Measure\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x0c\n\x04unit\x18\x02 \x01(\t\"\xcf\x01\n\tImageInfo\x12\x0f\n\x07product\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x1e\n\x07measure\x18\x04 \x01(\x0b\x32\x08.MeasureH\x00\x88\x01\x01\x12.\n\nattributes\x18\x05 \x03(\x0b\x32\x1a.ImageInfo.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_measure2D\n\x17PriceTagAnalyzerService\x12)\n\x0c\x41nalyzeImage\x12\x0b.ImageChunk\x1a\n.ImageInfo(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'price_tag_analyzer.grpc_compiled.PriceTagAnalyzerService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEINFO_ATTRIBUTESENTRY']._options = None
  _globals['_IMAGEINFO_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_IMAGECHUNK']._serialized_start=66
  _globals['_IMAGECHUNK']._serialized_end=95
  _globals['_MEASURE']._serialized_start=97
  _globals['_MEASURE']._serialized_end=136
  _globals['_IMAGEINFO']._serialized_start=139
  _globals['_IMAGEINFO']._serialized_end=346
  _globals['_IMAGEINFO_ATTRIBUTESENTRY']._serialized_start=285
  _globals['_IMAGEINFO_ATTRIBUTESENTRY']._serialized_end=334
  _globals['_PRICETAGANALYZERSERVICE']._serialized_start=348
  _globals['_PRICETAGANALYZERSERVICE']._serialized_end=416
# @@protoc_insertion_point(module_scope)
