# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from price_tag_analyzer.grpc_compiled import PriceTagAnalyzerService_pb2 as price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2


class PriceTagAnalyzerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeImage = channel.stream_unary(
                '/PriceTagAnalyzerService/AnalyzeImage',
                request_serializer=price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageChunk.SerializeToString,
                response_deserializer=price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageInfo.FromString,
                )


class PriceTagAnalyzerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceTagAnalyzerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeImage': grpc.stream_unary_rpc_method_handler(
                    servicer.AnalyzeImage,
                    request_deserializer=price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageChunk.FromString,
                    response_serializer=price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PriceTagAnalyzerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PriceTagAnalyzerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/PriceTagAnalyzerService/AnalyzeImage',
            price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageChunk.SerializeToString,
            price__tag__analyzer_dot_grpc__compiled_dot_PriceTagAnalyzerService__pb2.ImageInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
